import fs from "fs";
import path from "path";
import http from "http";

const LOG_DIR = path.join(process.cwd(), "logs");
const LOG_FILE = path.join(LOG_DIR, "app.log");

let isWriting = false;

// Ensure logs directory exists
if (typeof window === "undefined") {
  if (!fs.existsSync(LOG_DIR)) {
    fs.mkdirSync(LOG_DIR, { recursive: true });
  }

  // Create the log file if it doesn't exist
  if (!fs.existsSync(LOG_FILE)) {
    fs.writeFileSync(
      LOG_FILE,
      `[${new Date().toISOString()}] [SYSTEM] Logging initialized.\n`,
      "utf8"
    );
  }
}

// Helper to strip ANSI escape codes (terminal colors, etc.)
function stripAnsi(str: string): string {
  return str.replace(
    /[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g,
    ""
  );
}

function writeRawLog(chunk: string | Uint8Array) {
  if (isWriting) return;
  isWriting = true;
  try {
    const rawText = typeof chunk === "string" ? chunk : new TextDecoder().decode(chunk);
    const text = stripAnsi(rawText);

    // Split by newline to format and timestamp each line
    const lines = text.split("\n");
    let formattedText = "";

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      // Skip the last line if it's empty (which is normal if chunk ends in \n)
      if (i === lines.length - 1 && !line) break;

      const trimmed = line.trim();
      if (!trimmed) continue;

      const timestamp = new Date().toISOString();
      let level = "INFO";

      if (
        trimmed.toLowerCase().includes("error") ||
        trimmed.toLowerCase().includes("fail") ||
        trimmed.includes("Exception")
      ) {
        level = "ERROR";
      } else if (
        trimmed.toLowerCase().includes("warn") ||
        trimmed.toLowerCase().includes("deprecat")
      ) {
        level = "WARN";
      } else if (trimmed.includes("[SYSTEM]")) {
        level = "SYSTEM";
      }

      // Avoid double timestamping if the log line was already generated by our logger
      if (trimmed.match(/^\[\d{4}-\d{2}-\d{2}T/)) {
        formattedText += `${trimmed}\n`;
      } else {
        formattedText += `[${timestamp}] [${level}] ${trimmed}\n`;
      }
    }

    if (formattedText) {
      fs.appendFileSync(LOG_FILE, formattedText, "utf8");
    }
  } catch (err) {
    // Fail silently to avoid crash loops
  } finally {
    isWriting = false;
  }
}

// Intercept low-level stdout/stderr once on startup (server-side only)
if (typeof window === "undefined" && !(global as any).__logger_initialized) {
  (global as any).__logger_initialized = true;

  const originalStdoutWrite = process.stdout.write;
  const originalStderrWrite = process.stderr.write;

  // Intercept standard output
  process.stdout.write = function (
    chunk: any,
    encoding?: any,
    callback?: any
  ): boolean {
    const result = originalStdoutWrite.call(process.stdout, chunk, encoding, callback);
    writeRawLog(chunk);
    return result;
  };

  // Intercept standard error
  process.stderr.write = function (
    chunk: any,
    encoding?: any,
    callback?: any
  ): boolean {
    const result = originalStderrWrite.call(process.stderr, chunk, encoding, callback);
    writeRawLog(chunk);
    return result;
  };

  // Override standard console helper methods to route through stdout/stderr
  console.log = (...args) => {
    const msg = args.map((a) => (typeof a === "object" ? JSON.stringify(a) : String(a))).join(" ");
    process.stdout.write(msg + "\n");
  };

  console.error = (...args) => {
    const msg = args.map((a) => (typeof a === "object" ? JSON.stringify(a) : String(a))).join(" ");
    process.stderr.write(msg + "\n");
  };

  console.warn = (...args) => {
    const msg = args.map((a) => (typeof a === "object" ? JSON.stringify(a) : String(a))).join(" ");
    process.stderr.write(msg + "\n");
  };

  // Intercept low-level Node.js http server responses to log response headers, status, and body
  const originalWrite = http.ServerResponse.prototype.write;
  const originalEnd = http.ServerResponse.prototype.end;
  const originalWriteHead = http.ServerResponse.prototype.writeHead;

  http.ServerResponse.prototype.writeHead = function (
    statusCode: number,
    ...args: any[]
  ) {
    (this as any).__statusCode = statusCode;
    return originalWriteHead.apply(this, arguments as any);
  };

  http.ServerResponse.prototype.write = function (
    chunk: any,
    encoding?: any,
    callback?: any
  ) {
    if (chunk) {
      if (!(this as any).__chunks) (this as any).__chunks = [];
      const buf = Buffer.isBuffer(chunk)
        ? chunk
        : Buffer.from(chunk, (typeof encoding === "string" ? encoding : "utf8") as BufferEncoding);
      (this as any).__chunks.push(buf);
    }
    return originalWrite.apply(this, arguments as any);
  };

  http.ServerResponse.prototype.end = function (
    chunk?: any,
    encoding?: any,
    callback?: any
  ) {
    if (chunk) {
      if (!(this as any).__chunks) (this as any).__chunks = [];
      const buf = Buffer.isBuffer(chunk)
        ? chunk
        : Buffer.from(chunk, (typeof encoding === "string" ? encoding : "utf8") as BufferEncoding);
      (this as any).__chunks.push(buf);
    }

    try {
      const res = this;
      const req = res.req;
      if (req) {
        const url = req.url || "";
        if (
          !url.startsWith("/api/admin/logs") &&
          !url.startsWith("/admin/logs") &&
          !url.includes(".")
        ) {
          const method = req.method;
          const statusCode = res.statusCode || (res as any).__statusCode || 200;
          const headers = { ...res.getHeaders() };
          for (const key of Object.keys(headers)) {
            const lowerKey = key.toLowerCase();
            if (
              lowerKey === "set-cookie" ||
              lowerKey === "cookie" ||
              lowerKey === "authorization" ||
              lowerKey === "proxy-authorization"
            ) {
              headers[key] = "[REDACTED]";
            }
          }
          const contentType = String(headers["content-type"] || "");

          let body = "";
          if (
            contentType.includes("application/json") ||
            contentType.includes("text/") ||
            contentType.includes("javascript")
          ) {
            const buffer = Buffer.concat((res as any).__chunks || []);
            body = buffer.toString("utf8");
            if (body.length > 2000) {
              body = body.slice(0, 2000) + "... [truncated]";
            }
          }

          const resLog = `[HTTP RES] ${method} ${url} -> ${statusCode}
  Headers: ${JSON.stringify(headers)}
  Body: ${body || "None"}\n`;
          writeRawLog(resLog);
          originalStdoutWrite.call(process.stdout, resLog);
        }
      }
    } catch (e) {
      // Ignore
    } finally {
      delete (this as any).__chunks;
    }

    return originalEnd.apply(this, arguments as any);
  };
}

export function getLogFilePath() {
  return LOG_FILE;
}
