import fs from "fs";
import path from "path";

const LOG_DIR = path.join(process.cwd(), "logs");
const LOG_FILE = path.join(LOG_DIR, "app.log");

let isWriting = false;

// Ensure logs directory exists
if (typeof window === "undefined") {
  if (!fs.existsSync(LOG_DIR)) {
    fs.mkdirSync(LOG_DIR, { recursive: true });
  }

  // Create the log file if it doesn't exist
  if (!fs.existsSync(LOG_FILE)) {
    fs.writeFileSync(
      LOG_FILE,
      `[${new Date().toISOString()}] [SYSTEM] Logging initialized.\n`,
      "utf8"
    );
  }
}

// Helper to strip ANSI escape codes (terminal colors, etc.)
function stripAnsi(str: string): string {
  return str.replace(
    /[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g,
    ""
  );
}

function writeRawLog(chunk: string | Uint8Array) {
  if (isWriting) return;
  isWriting = true;
  try {
    const rawText = typeof chunk === "string" ? chunk : new TextDecoder().decode(chunk);
    const text = stripAnsi(rawText);

    // Split by newline to format and timestamp each line
    const lines = text.split("\n");
    let formattedText = "";

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      // Skip the last line if it's empty (which is normal if chunk ends in \n)
      if (i === lines.length - 1 && !line) break;

      const trimmed = line.trim();
      if (!trimmed) continue;

      const timestamp = new Date().toISOString();
      let level = "INFO";

      if (
        trimmed.toLowerCase().includes("error") ||
        trimmed.toLowerCase().includes("fail") ||
        trimmed.includes("Exception")
      ) {
        level = "ERROR";
      } else if (
        trimmed.toLowerCase().includes("warn") ||
        trimmed.toLowerCase().includes("deprecat")
      ) {
        level = "WARN";
      } else if (trimmed.includes("[SYSTEM]")) {
        level = "SYSTEM";
      }

      // Avoid double timestamping if the log line was already generated by our logger
      if (trimmed.match(/^\[\d{4}-\d{2}-\d{2}T/)) {
        formattedText += `${trimmed}\n`;
      } else {
        formattedText += `[${timestamp}] [${level}] ${trimmed}\n`;
      }
    }

    if (formattedText) {
      fs.appendFileSync(LOG_FILE, formattedText, "utf8");
    }
  } catch (err) {
    // Fail silently to avoid crash loops
  } finally {
    isWriting = false;
  }
}

// Intercept low-level stdout/stderr once on startup (server-side only)
if (typeof window === "undefined" && !(global as any).__logger_initialized) {
  (global as any).__logger_initialized = true;

  const originalStdoutWrite = process.stdout.write;
  const originalStderrWrite = process.stderr.write;

  // Intercept standard output
  process.stdout.write = function (
    chunk: any,
    encoding?: any,
    callback?: any
  ): boolean {
    const result = originalStdoutWrite.call(process.stdout, chunk, encoding, callback);
    writeRawLog(chunk);
    return result;
  };

  // Intercept standard error
  process.stderr.write = function (
    chunk: any,
    encoding?: any,
    callback?: any
  ): boolean {
    const result = originalStderrWrite.call(process.stderr, chunk, encoding, callback);
    writeRawLog(chunk);
    return result;
  };

  // Override standard console helper methods to route through stdout/stderr
  console.log = (...args) => {
    const msg = args.map((a) => (typeof a === "object" ? JSON.stringify(a) : String(a))).join(" ");
    process.stdout.write(msg + "\n");
  };

  console.error = (...args) => {
    const msg = args.map((a) => (typeof a === "object" ? JSON.stringify(a) : String(a))).join(" ");
    process.stderr.write(msg + "\n");
  };

  console.warn = (...args) => {
    const msg = args.map((a) => (typeof a === "object" ? JSON.stringify(a) : String(a))).join(" ");
    process.stderr.write(msg + "\n");
  };
}

export function getLogFilePath() {
  return LOG_FILE;
}
